export const SET_LOADING = "SET_LOADING";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const SET_USER = "SET_USER";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_PLACES_SUCCESS = "CREATE_PLACES_SUCCESS";
export const CREATE_PLACES_ERROR = "CREATE_PLACES_ERROR";
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
export const FETCH_PLACES_ERROR = "FETCH_PLACES_ERROR";
export const FETCH_SINGLE_PLACE_SUCCESS = "FETCH_SINGLE_PLACE_SUCCESS";
export const FETCH_SINGLE_PLACE_ERROR = "FETCH_SINGLE_PLACE_ERROR";
export const EDIT_PLACE_ERROR = "EDIT_PLACE_ERROR";
export const EDIT_PLACE_SUCCESS = "EDIT_PLACE_SUCCESS";
export const EDIT_PROGRESS = "EDIT_PROGRESS";

export const FETCH_ALL_PLACES_SUCCESS = "FETCH_ALL_PLACES_SUCCESS";
export const FETCH_ALL_PLACES_ERROR = "FETCH_ALL_PLACES_ERROR";

export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_ERROR = "CREATE_BOOKING_ERROR";
export const FETCH_ALL_BOOKINGS_SUCCESS = "FETCH_ALL_BOOKINGS_SUCCESS";
export const FETCH_ALL_BOOKINGS_ERROR = "FETCH_ALL_BOOKINGS_ERROR";

// export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
// export const FETCH_JOBS_ERROR = "FETCH_JOBS_ERROR";
// export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
// export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";
// export const DELETE_JOB_ERROR = "DELETE_JOB_ERROR";
// export const FETCH_SINGLE_JOB_SUCCESS = "FETCH_SINGLE_JOB_SUCCESS";
// export const FETCH_SINGLE_JOB_ERROR = "FETCH_SINGLE_JOB_ERROR";

// export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
// export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";
